In [236]:
import pandas as pd
import json
import tensorflow 
from tensorflow import keras
from sklearn.feature_extraction.text import CountVectorizer
from joblib import dump
import numpy as np

In [237]:
with open('../intents.json', 'r') as f:
    intents=json.load(f)
intents = intents['intent']
intents

[{'tag': 'greeting',
  'patterns': ['Hi',
   'How are you?',
   'Hey there, how have you been?',
   'Is anyone there?',
   'Hello',
   'Good day'],
  'responses': ['Hi there, what can I do for you?',
   'Hey there, how can I help?']},
 {'tag': 'goodbye',
  'patterns': ['Bye', 'See you there', 'Goodbye'],
  'responses': ['See you later, thanks for visiting',
   'Have a nice day',
   'Bye! Come back again soon.']},
 {'tag': 'thanks',
  'patterns': ['Thanks', 'Thank you', "That's helpful", 'Nice', 'Good'],
  'responses': ['Happy to help!', 'Any time!', 'My pleasure']},
 {'tag': 'about',
  'patterns': ['about you',
   'Who are you?',
   'What are you?',
   'Who you are?',
   'what you can do',
   'What is the Purpose of the project'],
  'responses': ['I am AyurBot. I can help determine your prakriti type. Prakriti is our inherent nature, with which we are born. It is the nature of our body in terms of dosha. It dies not change during the whole lifetime. It is also responsible for the physi

In [238]:
for intent in intents:
    print(intent)

{'tag': 'greeting', 'patterns': ['Hi', 'How are you?', 'Hey there, how have you been?', 'Is anyone there?', 'Hello', 'Good day'], 'responses': ['Hi there, what can I do for you?', 'Hey there, how can I help?']}
{'tag': 'goodbye', 'patterns': ['Bye', 'See you there', 'Goodbye'], 'responses': ['See you later, thanks for visiting', 'Have a nice day', 'Bye! Come back again soon.']}
{'tag': 'thanks', 'patterns': ['Thanks', 'Thank you', "That's helpful", 'Nice', 'Good'], 'responses': ['Happy to help!', 'Any time!', 'My pleasure']}
{'tag': 'about', 'patterns': ['about you', 'Who are you?', 'What are you?', 'Who you are?', 'what you can do', 'What is the Purpose of the project'], 'responses': ['I am AyurBot. I can help determine your prakriti type. Prakriti is our inherent nature, with which we are born. It is the nature of our body in terms of dosha. It dies not change during the whole lifetime. It is also responsible for the physical and mental characteristics.']}
{'tag': 'name', 'patterns':

In [239]:
tags=[]
xy=[]
len_dict=0
for intent in intents:
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns']:
        len_dict=len_dict + 1
        w = pattern
        xy.append((w,tag))
print(xy)

[('Hi', 'greeting'), ('How are you?', 'greeting'), ('Hey there, how have you been?', 'greeting'), ('Is anyone there?', 'greeting'), ('Hello', 'greeting'), ('Good day', 'greeting'), ('Bye', 'goodbye'), ('See you there', 'goodbye'), ('Goodbye', 'goodbye'), ('Thanks', 'thanks'), ('Thank you', 'thanks'), ("That's helpful", 'thanks'), ('Nice', 'thanks'), ('Good', 'thanks'), ('about you', 'about'), ('Who are you?', 'about'), ('What are you?', 'about'), ('Who you are?', 'about'), ('what you can do', 'about'), ('What is the Purpose of the project', 'about'), ('what is your name', 'name'), ('what should I call you', 'name'), ('whats your name?', 'name'), ('Could you help me?', 'help'), ('give me a hand please', 'help'), ('Can you help?', 'help'), ('What can you do for me?', 'help'), ('I need a support', 'help'), ('I need a help', 'help'), ('support me please', 'help'), ('Complete the work', 'noanswer'), ('My name', 'noanswer'), ('user name', 'noanswer'), ('you are not Good', 'noanswer'), ('Noth

In [240]:
tags=[]
xy=[]
len_dict=0
for intent in intents:
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns']:
        len_dict=len_dict + 1
        w = pattern
        xy.append((w,tag))
df = pd.DataFrame(xy)
df.rename(columns = {0:"Sentence", 1:"Target"}, inplace = True)
named_y = df['Target']
df

Sentence       Target
0                              Hi     greeting
1                    How are you?     greeting
2   Hey there, how have you been?     greeting
3                Is anyone there?     greeting
4                           Hello     greeting
..                            ...          ...
61                  I despise you     badwords
62                             ok  acknowledge
63                           yeah  acknowledge
64            This should be best  acknowledge
65               Now I Understand  acknowledge

[66 rows x 2 columns]

In [241]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
print(df['Target'])

0        greeting
1        greeting
2        greeting
3        greeting
4        greeting
         ...     
61       badwords
62    acknowledge
63    acknowledge
64    acknowledge
65    acknowledge
Name: Target, Length: 66, dtype: object


In [242]:
df['Target'] = lb.fit_transform(df['Target'])
df["Target"]

0     5
1     5
2     5
3     5
4     5
     ..
61    2
62    1
63    1
64    1
65    1
Name: Target, Length: 66, dtype: int32

In [243]:
df

Sentence  Target
0                              Hi       5
1                    How are you?       5
2   Hey there, how have you been?       5
3                Is anyone there?       5
4                           Hello       5
..                            ...     ...
61                  I despise you       2
62                             ok       1
63                           yeah       1
64            This should be best       1
65               Now I Understand       1

[66 rows x 2 columns]

In [244]:
df.set_index('Sentence')
df

Sentence  Target
0                              Hi       5
1                    How are you?       5
2   Hey there, how have you been?       5
3                Is anyone there?       5
4                           Hello       5
..                            ...     ...
61                  I despise you       2
62                             ok       1
63                           yeah       1
64            This should be best       1
65               Now I Understand       1

[66 rows x 2 columns]

In [245]:
df.reset_index(drop=True)
df.to_csv('../dataset/sentences_intent.csv')
df

Sentence  Target
0                              Hi       5
1                    How are you?       5
2   Hey there, how have you been?       5
3                Is anyone there?       5
4                           Hello       5
..                            ...     ...
61                  I despise you       2
62                             ok       1
63                           yeah       1
64            This should be best       1
65               Now I Understand       1

[66 rows x 2 columns]

In [246]:
X_train = df.Sentence
y_train = df.Target

In [247]:
X_train

0                                Hi
1                      How are you?
2     Hey there, how have you been?
3                  Is anyone there?
4                             Hello
                  ...              
61                    I despise you
62                               ok
63                             yeah
64              This should be best
65                 Now I Understand
Name: Sentence, Length: 66, dtype: object

In [248]:
y_train

0     5
1     5
2     5
3     5
4     5
     ..
61    2
62    1
63    1
64    1
65    1
Name: Target, Length: 66, dtype: int32

In [249]:
labels = {}
for i in range(len_dict):
    labels[y_train[i]] = named_y[i]
labels

{5: 'greeting',
 4: 'goodbye',
 10: 'thanks',
 0: 'about',
 7: 'name',
 6: 'help',
 8: 'noanswer',
 9: 'prakriti',
 3: 'creators',
 2: 'badwords',
 1: 'acknowledge'}

In [250]:
len_dict

66

In [251]:
named_y.value_counts()

Target
badwords       10
noanswer        9
help            7
creators        7
greeting        6
about           6
prakriti        6
thanks          5
acknowledge     4
goodbye         3
name            3
Name: count, dtype: int64

In [252]:
vec = CountVectorizer(min_df=1)

In [253]:
X_train_count = vec.fit_transform(X_train.values)
X_train_count.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0], dtype=int64)

In [254]:
bag_len = len(X_train_count.toarray()[0])
bag_len

89

In [255]:
df_bow = pd.DataFrame(X_train_count.toarray(), columns=vec.get_feature_names_out())
df_bow

about  annoying  anyone  are  away  bad  be  been  best  by  ...  what  \
0       0         0       0    0     0    0   0     0     0   0  ...     0   
1       0         0       0    1     0    0   0     0     0   0  ...     0   
2       0         0       0    0     0    0   0     1     0   0  ...     0   
3       0         0       1    0     0    0   0     0     0   0  ...     0   
4       0         0       0    0     0    0   0     0     0   0  ...     0   
..    ...       ...     ...  ...   ...  ...  ..   ...   ...  ..  ...   ...   
61      0         0       0    0     0    0   0     0     0   0  ...     0   
62      0         0       0    0     0    0   0     0     0   0  ...     0   
63      0         0       0    0     0    0   0     0     0   0  ...     0   
64      0         0       0    0     0    0   1     0     1   0  ...     0   
65      0         0       0    0     0    0   0     0     0   0  ...     0   

    whats  which  who  work  worry  worthless  yeah  you  your  
0       0      0    0     0      0          0     0    0     0  
1       0      0    0     0      0          0     0    1     0  
2       0      0    0     0      0          0     0    1     0  
3       0      0    0     0      0          0     0    0     0  
4       0      0    0     0      0          0     0    0     0  
..    ...    ...  ...   ...    ...        ...   ...  ...   ...  
61      0      0    0     0      0          0     0    1     0  
62      0      0    0     0      0          0     0    0     0  
63      0      0    0     0      0          0     1    0     0  
64      0      0    0     0      0          0     0    0     0  
65      0      0    0     0      0          0     0    0     0  

[66 rows x 89 columns]

In [256]:
X_train=df_bow.to_numpy()
print(X_train)
print(X_train_count)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  (0, 37)	1
  (1, 38)	1
  (1, 3)	1
  (1, 87)	1
  (2, 38)	1
  (2, 87)	1
  (2, 36)	1
  (2, 72)	1
  (2, 32)	1
  (2, 7)	1
  (3, 72)	1
  (3, 41)	1
  (3, 2)	1
  (4, 33)	1
  (5, 28)	1
  (5, 18)	1
  (6, 10)	1
  (7, 87)	1
  (7, 72)	1
  (7, 61)	1
  (8, 29)	1
  (9, 69)	1
  (10, 87)	1
  (10, 68)	1
  (11, 70)	1
  :	:
  (56, 60)	1
  (56, 65)	1
  (56, 1)	1
  (57, 87)	1
  (57, 12)	1
  (57, 66)	1
  (58, 27)	1
  (58, 4)	1
  (59, 87)	1
  (59, 60)	1
  (59, 85)	1
  (60, 87)	1
  (60, 44)	1
  (60, 43)	1
  (60, 64)	1
  (61, 87)	1
  (61, 19)	1
  (62, 54)	1
  (63, 86)	1
  (64, 62)	1
  (64, 8)	1
  (64, 74)	1
  (64, 6)	1
  (65, 52)	1
  (65, 76)	1


In [257]:
model = keras.Sequential([
    keras.layers.Dense(1000, input_shape=(bag_len,),activation='relu',),
    keras.layers.Dense(100,activation='relu',),
    keras.layers.Dense(11,activation='sigmoid',)
])

In [258]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(X_train, y_train, epochs=100)

Epoch 1/100


3/3 [==============================] - 1s 4ms/step - loss: 2.3919 - accuracy: 0.1212
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 2.2318 - accuracy: 0.5606
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 2.1020 - accuracy: 0.6212
Epoch 4/100
3/3 [==============================] - 0s 8ms/step - loss: 1.9737 - accuracy: 0.6515
Epoch 5/100
3/3 [==============================] - 0s 5ms/step - loss: 1.8431 - accuracy: 0.7121
Epoch 6/100
3/3 [==============================] - 0s 9ms/step - loss: 1.7124 - accuracy: 0.7727
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 1.5896 - accuracy: 0.8485
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 1.4707 - accuracy: 0.8939
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 1.3463 - accuracy: 0.9091
Epoch 10/100
3/3 [==============================] - 0s 6ms/step - loss: 1.2199 - accuracy: 0.9091
Epoch 11/100
3/3 [=======================

In [259]:
ndf=pd.read_csv("../dataset/sentences_intent.csv")
X_train=ndf.Sentence
X_train

0                                Hi
1                      How are you?
2     Hey there, how have you been?
3                  Is anyone there?
4                             Hello
                  ...              
61                    I despise you
62                               ok
63                             yeah
64              This should be best
65                 Now I Understand
Name: Sentence, Length: 66, dtype: object

In [266]:
data=vec.transform(["great"])

dfdata=pd.DataFrame(data.toarray(),columns=vec.get_feature_names_out())
dfdata.loc[:,dfdata.iloc[0,:]==1]

Empty DataFrame
Columns: []
Index: [0]

In [267]:
labels.get(np.argmax(model.predict(data)))

1/1 [==============================] - 0s 41ms/step


'thanks'

In [262]:
vec

CountVectorizer()

In [263]:
dump(model,"../Models/nlm")

['../Models/nlm']