In [1]:
import pandas as pd
import json
import tensorflow 
from tensorflow import keras
from sklearn.feature_extraction.text import CountVectorizer
from joblib import dump
import numpy as np

In [2]:
with open('../intents.json', 'r') as f:
    intents=json.load(f)
intents = intents['intent']
intents

[{'tag': 'greeting',
  'patterns': ['Hi',
   'How are you?',
   'Hey there, how have you been?',
   'Is anyone there?',
   'Hello',
   'Good day',
   'Hiii',
   'Hii'],
  'responses': ['Hi there, what can I do for you?',
   'Hey there, how can I help?']},
 {'tag': 'goodbye',
  'patterns': ['Bye', 'See you there', 'Goodbye'],
  'responses': ['See you later, thanks for visiting ',
   'Have a nice day',
   'Bye! Come back again soon.']},
 {'tag': 'thanks',
  'patterns': ['Thanks', 'Thank you', "That's helpful", 'Nice', 'Good'],
  'responses': ['Happy to help!', 'Any time!', 'My pleasure']},
 {'tag': 'about',
  'patterns': ['about you',
   'Who are you?',
   'What are you?',
   'Who you are?',
   'what you can do',
   'What is the Purpose of the project'],
  'responses': ['I am AyurBot. I can help determine your prakriti type. Prakriti is our inherent nature, with which we are born. It is the nature of our body in terms of dosha. It dies not change during the whole lifetime. It is also res

In [3]:
for intent in intents:
    print(intent)

{'tag': 'greeting', 'patterns': ['Hi', 'How are you?', 'Hey there, how have you been?', 'Is anyone there?', 'Hello', 'Good day', 'Hiii', 'Hii'], 'responses': ['Hi there, what can I do for you?', 'Hey there, how can I help?']}
{'tag': 'goodbye', 'patterns': ['Bye', 'See you there', 'Goodbye'], 'responses': ['See you later, thanks for visiting ', 'Have a nice day', 'Bye! Come back again soon.']}
{'tag': 'thanks', 'patterns': ['Thanks', 'Thank you', "That's helpful", 'Nice', 'Good'], 'responses': ['Happy to help!', 'Any time!', 'My pleasure']}
{'tag': 'about', 'patterns': ['about you', 'Who are you?', 'What are you?', 'Who you are?', 'what you can do', 'What is the Purpose of the project'], 'responses': ['I am AyurBot. I can help determine your prakriti type. Prakriti is our inherent nature, with which we are born. It is the nature of our body in terms of dosha. It dies not change during the whole lifetime. It is also responsible for the physical and mental characteristics.']}
{'tag': 'na

In [4]:
tags=[]
xy=[]
len_dict=0
for intent in intents:
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns']:
        len_dict=len_dict + 1
        w = pattern
        xy.append((w,tag))
print(xy)

[('Hi', 'greeting'), ('How are you?', 'greeting'), ('Hey there, how have you been?', 'greeting'), ('Is anyone there?', 'greeting'), ('Hello', 'greeting'), ('Good day', 'greeting'), ('Hiii', 'greeting'), ('Hii', 'greeting'), ('Bye', 'goodbye'), ('See you there', 'goodbye'), ('Goodbye', 'goodbye'), ('Thanks', 'thanks'), ('Thank you', 'thanks'), ("That's helpful", 'thanks'), ('Nice', 'thanks'), ('Good', 'thanks'), ('about you', 'about'), ('Who are you?', 'about'), ('What are you?', 'about'), ('Who you are?', 'about'), ('what you can do', 'about'), ('What is the Purpose of the project', 'about'), ('what is your name', 'name'), ('what should I call you', 'name'), ('whats your name?', 'name'), ('Could you help me?', 'help'), ('give me a hand please', 'help'), ('Can you help?', 'help'), ('What can you do for me?', 'help'), ('I need a support', 'help'), ('I need a help', 'help'), ('support me please', 'help'), ('Complete the work', 'noanswer'), ('My name', 'noanswer'), ('user name', 'noanswer'

In [5]:
tags=[]
xy=[]
len_dict=0
for intent in intents:
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns']:
        len_dict=len_dict + 1
        w = pattern
        xy.append((w,tag))
df = pd.DataFrame(xy)
df.rename(columns = {0:"Sentence", 1:"Target"}, inplace = True)
named_y = df['Target']
df

Sentence       Target
0                              Hi     greeting
1                    How are you?     greeting
2   Hey there, how have you been?     greeting
3                Is anyone there?     greeting
4                           Hello     greeting
..                            ...          ...
63                  I despise you     badwords
64                             ok  acknowledge
65                           yeah  acknowledge
66            This should be best  acknowledge
67               Now I Understand  acknowledge

[68 rows x 2 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
print(df['Target'])

0        greeting
1        greeting
2        greeting
3        greeting
4        greeting
         ...     
63       badwords
64    acknowledge
65    acknowledge
66    acknowledge
67    acknowledge
Name: Target, Length: 68, dtype: object


In [7]:
df['Target'] = lb.fit_transform(df['Target'])
df["Target"]

0     5
1     5
2     5
3     5
4     5
     ..
63    2
64    1
65    1
66    1
67    1
Name: Target, Length: 68, dtype: int32

In [8]:
df

Sentence  Target
0                              Hi       5
1                    How are you?       5
2   Hey there, how have you been?       5
3                Is anyone there?       5
4                           Hello       5
..                            ...     ...
63                  I despise you       2
64                             ok       1
65                           yeah       1
66            This should be best       1
67               Now I Understand       1

[68 rows x 2 columns]

In [9]:
df.set_index('Sentence')
df

Sentence  Target
0                              Hi       5
1                    How are you?       5
2   Hey there, how have you been?       5
3                Is anyone there?       5
4                           Hello       5
..                            ...     ...
63                  I despise you       2
64                             ok       1
65                           yeah       1
66            This should be best       1
67               Now I Understand       1

[68 rows x 2 columns]

In [10]:
df.reset_index(drop=True)
df.to_csv('../dataset/sentences_intent.csv')
df

Sentence  Target
0                              Hi       5
1                    How are you?       5
2   Hey there, how have you been?       5
3                Is anyone there?       5
4                           Hello       5
..                            ...     ...
63                  I despise you       2
64                             ok       1
65                           yeah       1
66            This should be best       1
67               Now I Understand       1

[68 rows x 2 columns]

In [11]:
X_train = df.Sentence
y_train = df.Target

In [12]:
X_train

0                                Hi
1                      How are you?
2     Hey there, how have you been?
3                  Is anyone there?
4                             Hello
                  ...              
63                    I despise you
64                               ok
65                             yeah
66              This should be best
67                 Now I Understand
Name: Sentence, Length: 68, dtype: object

In [13]:
y_train

0     5
1     5
2     5
3     5
4     5
     ..
63    2
64    1
65    1
66    1
67    1
Name: Target, Length: 68, dtype: int32

In [14]:
labels = {}
for i in range(len_dict):
    labels[y_train[i]] = named_y[i]
labels

{5: 'greeting',
 4: 'goodbye',
 10: 'thanks',
 0: 'about',
 7: 'name',
 6: 'help',
 8: 'noanswer',
 9: 'prakriti',
 3: 'creators',
 2: 'badwords',
 1: 'acknowledge'}

In [15]:
len_dict

68

In [16]:
named_y.value_counts()

Target
badwords       10
noanswer        9
greeting        8
help            7
creators        7
about           6
prakriti        6
thanks          5
acknowledge     4
goodbye         3
name            3
Name: count, dtype: int64

In [17]:
vec = CountVectorizer(min_df=1)

In [18]:
X_train_count = vec.fit_transform(X_train.values)
X_train_count.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [19]:
bag_len = len(X_train_count.toarray()[0])
bag_len

91

In [20]:
df_bow = pd.DataFrame(X_train_count.toarray(), columns=vec.get_feature_names_out())
df_bow

about  annoying  anyone  are  away  bad  be  been  best  by  ...  what  \
0       0         0       0    0     0    0   0     0     0   0  ...     0   
1       0         0       0    1     0    0   0     0     0   0  ...     0   
2       0         0       0    0     0    0   0     1     0   0  ...     0   
3       0         0       1    0     0    0   0     0     0   0  ...     0   
4       0         0       0    0     0    0   0     0     0   0  ...     0   
..    ...       ...     ...  ...   ...  ...  ..   ...   ...  ..  ...   ...   
63      0         0       0    0     0    0   0     0     0   0  ...     0   
64      0         0       0    0     0    0   0     0     0   0  ...     0   
65      0         0       0    0     0    0   0     0     0   0  ...     0   
66      0         0       0    0     0    0   1     0     1   0  ...     0   
67      0         0       0    0     0    0   0     0     0   0  ...     0   

    whats  which  who  work  worry  worthless  yeah  you  your  
0       0      0    0     0      0          0     0    0     0  
1       0      0    0     0      0          0     0    1     0  
2       0      0    0     0      0          0     0    1     0  
3       0      0    0     0      0          0     0    0     0  
4       0      0    0     0      0          0     0    0     0  
..    ...    ...  ...   ...    ...        ...   ...  ...   ...  
63      0      0    0     0      0          0     0    1     0  
64      0      0    0     0      0          0     0    0     0  
65      0      0    0     0      0          0     1    0     0  
66      0      0    0     0      0          0     0    0     0  
67      0      0    0     0      0          0     0    0     0  

[68 rows x 91 columns]

In [21]:
X_train=df_bow.to_numpy()
print(X_train)
print(X_train_count)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  (0, 37)	1
  (1, 40)	1
  (1, 3)	1
  (1, 89)	1
  (2, 40)	1
  (2, 89)	1
  (2, 36)	1
  (2, 74)	1
  (2, 32)	1
  (2, 7)	1
  (3, 74)	1
  (3, 43)	1
  (3, 2)	1
  (4, 33)	1
  (5, 28)	1
  (5, 18)	1
  (6, 39)	1
  (7, 38)	1
  (8, 10)	1
  (9, 89)	1
  (9, 74)	1
  (9, 63)	1
  (10, 29)	1
  (11, 71)	1
  (12, 89)	1
  :	:
  (58, 62)	1
  (58, 67)	1
  (58, 1)	1
  (59, 89)	1
  (59, 12)	1
  (59, 68)	1
  (60, 27)	1
  (60, 4)	1
  (61, 89)	1
  (61, 62)	1
  (61, 87)	1
  (62, 89)	1
  (62, 46)	1
  (62, 45)	1
  (62, 66)	1
  (63, 89)	1
  (63, 19)	1
  (64, 56)	1
  (65, 88)	1
  (66, 64)	1
  (66, 8)	1
  (66, 76)	1
  (66, 6)	1
  (67, 54)	1
  (67, 78)	1


In [22]:
model = keras.Sequential([
    keras.layers.Dense(1000, input_shape=(bag_len,),activation='relu',),
    keras.layers.Dense(100,activation='relu',),
    keras.layers.Dense(11,activation='sigmoid',)
])

In [23]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 8ms/step - loss: 2.4094 - accuracy: 0.1029
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 2.3609 - accuracy: 0.1765
Epoch 3/100
3/3 [==============================] - 0s 5ms/step - loss: 2.3249 - accuracy: 0.2059
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 2.2879 - accuracy: 0.2206
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 2.2541 - accuracy: 0.3088
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 2.2206 - accuracy: 0.4412
Epoch 7/100
3/3 [==============================] - 0s 6ms/step - loss: 2.1877 - accuracy: 0.4559
Epoch 8/100
3/3 [==============================] - 0s 4ms/step - loss: 2.1535 - accuracy: 0.4853
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 2.1184 - accuracy: 0.5441
Epoch 10/100
3/3 [==============================] - 0s 6ms/step - loss: 2.0832 - accuracy: 0.5735
Epoch 11/100
3/3 [===========

In [24]:
ndf=pd.read_csv("../dataset/sentences_intent.csv")
X_train=ndf.Sentence
X_train

0                                Hi
1                      How are you?
2     Hey there, how have you been?
3                  Is anyone there?
4                             Hello
                  ...              
63                    I despise you
64                               ok
65                             yeah
66              This should be best
67                 Now I Understand
Name: Sentence, Length: 68, dtype: object

In [25]:
data=vec.transform(["great"])

dfdata=pd.DataFrame(data.toarray(),columns=vec.get_feature_names_out())
dfdata.loc[:,dfdata.iloc[0,:]==1]

Empty DataFrame
Columns: []
Index: [0]

In [26]:
labels.get(np.argmax(model.predict(data)))

1/1 [==============================] - 0s 213ms/step


'greeting'

In [27]:
vec

CountVectorizer()

In [28]:
dump(model,"../Models/nlm")

['../Models/nlm']